apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: nginx-loadbalancer-role
subjects:
 - kind: User
   name: nginx-loadbalancer-sa
   apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: nginx-loadbalancer-role
  apiGroup: rbac.authorization.k8s.io