# Use the official NGINX image as the base
FROM nginx:alpine

# Copy your local HTML files to the container
#COPY . /usr/share/nginx/html/

# Expose port 80
EXPOSE 80

# Start the NGINX server
CMD ["nginx", "-g", "daemon off;"]
